export const JWT_TOKEN_NAME = 'Authorization';

export const Messages = {
    Missing_Fields_Required: 'Missing required fields',
    User_Exists: 'User already exists',
    Register_Fail: 'registration failed',
    User_Not_Registered: 'User not found. Please register first',
    Login_Fail: 'Invalid credentials',
    Login_Sucess: 'Login successful',
    Register_Sucess: 'user registered successfully',
    User_Data_Fetched: "User data fetched successfully!",
    User_Updated: "User Updated successfully!",
    User_Deleted: "User Deleted successfully!",
    User_Created: "User Created successfully!",
    User_Not_Available: "User Not Available",
    User_Not_Found: 'User not found',
    Unauthorized_User: "Unauthorized",
    Duplicate_Email: "Duplicate Email",
    UserAuthenticated: "User Authenticated successfully!",
    Fetch_Error: "Error fetching users",
    Something_went_Wrong: "Something went wrong!",
    Internal_Server_Error: "Internal Server Error",
    Success: "Success",
    Fail: 'Fail',
    Not_Authorized_No_Token: "Not authorized, no token",
    Invalid_Token: "Invalid token.",
    Token_Expired: "Token expired. Please log in again.",
    Token_Expired_Error: "TokenExpiredError",
    Property_Updation_Failed: 'Updating property failed',
    Property_Updation_Success: 'Property updated successfully',
    Property_Creation_Failed: 'Creating property failed',
    Property_Creation_Success: 'Property created successfully',
    Property_Fetching_Success: 'Property fetched successfully',
    Property_Fetching_Fail: 'Propery fetching failed',
    Property_Not_Found: 'Property not found',
    Image_Adding: 'Image added sucessfully',
    Image_Adding_Failure: 'Adding image failed',
    Image_Fetching_Success: 'Image fetched successfully',
    Image_Fetching_Fail: 'Image fetching failed',
    Favorite_Adding: ' Favorite added sucessfully',
    Favorite_Adding_Failure: 'Adding  favorite failed',
    Favorite_Fetching_Success: ' Favorite fetched sucessfully',
    Favorite_Fetching_Failure: 'Fetching  favorite failed',
    Invalid_Images_Format: 'invalid image',
    Favorite_Removing_Success: 'Favorite removed successfully',
    Favorite_Not_Found: 'Favorite not found',
    Favorite_Removing_Failure: 'Removing favorite failed',
    Favorite_Already_Added: 'Already added in favorite',
    Invalid_Bucket_Name: 'Invalid bucket name',
    User_Fetching_Success: 'User fetched successfully!',
    User_Fetching_Fail: 'User fetch failed!',
    Request_Creation_Failed: 'Failed to create request',
    Invalid_Address: 'Invalid property address',
    Request_Fetching_Success: 'Request fetched successfully!',
    Request_Fetching_Fail: 'Request fetch failed!',
    Fail_Delete_Property: "Failed to delete property",
    Invalid_Property: 'Invalid property',
    Property_Deletion_Success: 'Property deleted successfully',
    Request_Not_Found: 'Request not found',
    Request_Update_Success: 'Request status updated successfully',
    Request_Update_Fail: 'Failed to update request status',
    Password_MissMatch: "Passwords do not match",
    Invalid_Credentials: "Invalid credentials",
    PhoneNumber_Required: 'Phone number is required',
    Invalid_PhoneNumber: 'Invalid phone number format. Use international format (e.g., +919739863915)',
    SMS_Unavailable: 'SMS service temporarily unavailable',
    Otp_Success: 'OTP sent successfully',
    PhoneNumberAndOtp_Required: 'Phone number and OTP are required',
    InvalidOtp_Format:'Invalid OTP format. Must be 4-6 digits',
    OtpVerification_Success:'OTP verified successfully'

}