export const ALL_AMENITIES = [
  "closed_parking",
  "open_parking",
  "visitor_parking",
  "water_storage",
  "security_fire_alarm",
  "lift",
  "park",
  "vastu_compliant",
  "high_ceiling_height",
  "piped_gas",
  "internet_wifi_connectivity",
  "shopping_center",
  "swimming_pool",
  "fitness_centre_gym",
  "waste_disposal",
  "rain_water_harvesting",
  "borewell",
  "24x7_water",
  "pool",
  "wheelchair_friendly",
  "pet_friendly",
  "close_to_metro_station",
  "close_to_market",
  "close_to_school",
  "full",
  "partial",
  "none",
  "furnished",
  "semi_furnished",
  "unfurnished",
];

export const formatAmenity = (value: string) =>
  value.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
